__version__ = "0.1.0"
__title__ = "speech_to_text"
__description__ = "Fancy (future) command line tool for converting speech into text"
__url__ = "https://github.com/gregdan3/speech-to-text"
__author__ = "Gregory Danielson"
__author_email__ = "gregory.danielson3@gmail.com"
__copyright__ = "Copyright Gregory Danielson, 2020. All rights reserved."
